spring:
  application.name: BlogService
  profiles.active: dev

---
spring:
  sql.init.mode: always
  config.activate.on-profile: dev
  devtools.restart.enabled: true
  application:
    name: BlogService
  datasource:
    url: "jdbc:h2:mem:blogdb"
    driverClassName: org.h2.Driver
    username: root
    password: root
    data: schema.sql
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true
    console.path: /h2-ui

server:
  servlet.contextPath: /api
  port: 8080

logging:
  level:
    root: INFO